### ISSUE TITLE
the calculation of attention in SNnet_attention_block.py  is wrong 

### ISSUE THREAD

**Issue by l2009312042** [Gitxiaoke/SNnet#1]
for example  to calculate the temporal attention  ，the shape of the attention matrix is T  *  T，in the code，is C/2 * C/2，which is not match.

you should reshap the feature to  B ,T,(F*C/2), it is a  three tuple ,not  four  tuple

**Comment by Gitxiaoke** [comment]
I don't understand what you mean, can you give me the code

**Comment by Gitxiaoke** [comment]
Thank you very much. I have read the paper again, and in the paper, the time axis or frequency axis of each channel is connected. My code is indeed wrong, and I will put out my corrected code later
